GriddleGriddle/Griddle

.travis.yml

Just gotta flip the switch in the travis-ci dashboard for DynamicTyped/Griddle
https://travis-ci.org/scvnc/Griddle/builds/47996232

Initial travis-ci config

---

build/griddle.js
docs/assets/index.html
examples/assets/scripts/fakeData.js
scripts/__tests__/griddle-test.js
scripts/gridRowContainer.jsx
scripts/gridTable.jsx
scripts/griddle.jsx
scripts/rowProperties.js

This should provide consistent keys based on a column in the table to help with #104.

Updated grid to allow user to send in unique ID field via rowMetadata

---

scripts/gridSettings.jsx

add a key to rendered column checkboxes in GridSettings

---

scripts/columnProperties.js
scripts/griddle.jsx

so they appear in the same order there as in the table

sort the columns in grid settings

---

scripts/gridRow.jsx
scripts/gridRowContainer.jsx

Apparently passing `false` as a value of `style` prop is not working

Avoid passing userGriddleStyles as style prop

---

scripts/gridRowContainer.jsx

Not sure if this is the best solution, but it work and I don't want to mess with circular dependencies

Don't rely on global Griddle

---

scripts/griddle.jsx

This should fix https://github.com/GriddleGriddle/Griddle/issues/120

Switched from _.rest to _.drop

---

docs/src/markdown/customization.md

This is an undocumented feature that allows you to style a row based on the rows data.

Document how to style an individual row.

---

docs/src/markdown/customization.md

Update customization.md - rowMetaData to rowMetadata

---

scripts/gridRow.jsx

Use _.extend instead of Object.create to preserve data

Fix for issue #184

---

customization.html
scripts/ChartistGraph.js
scripts/Griddle.js
styling.html

This should update the docs with the latest contents from the markdown files on the `master` branch...I just ran the `grunt build` task and copied the generated contents from `/docs/html` over.
Ideally, this would be automated via a npm post-publish script or on a CI server

Updating gh-pages with latest docs

---

build/griddle.js
scripts/__tests__/griddle-test.js
scripts/customFilterContainer.jsx
scripts/griddle.jsx

The pull request enables
- The ability of specify a custom filter component, to enable
- Building complex filter inputs, filters with more components than the simple text box
- Faceting, the result set is passed down to the filter, so that the filter can change according to what is selected.
- The ability to specify a custom filter function, to enable
- Swapping out the underscore based filterer, to a more performant alternative. 
- Enables consumption of the custom filter object that the customFilterComponent might create.

Custom filterComponent and filter function

---

docs/src/markdown/infiniteScroll.md

Had the markdown syntax for the link incorrect.

Update infiniteScroll.md - fix markdown syntax for link

---

README.md

Updated to point to new repo and remove the is:pr filter.

Fix link to issues

---

docs/src/markdown/customization.md
examples/properties/properties.html

Custom Filtering and a Custom Filter Component was added in https://github.com/GriddleGriddle/Griddle/pull/238. In this PR I am adding documentation and an example of how to use this awesome functionality based on my experience using it.
I couldn't see any info on how the docs work so hopefully I figured it out properly. Happy to make any changes required.
cc @tinygrasshopper in case you want to check the documentation for correctness

Add Docs for Custom Filter function and Component

---

build/Griddle.js
examples/customization/customColumn.html
package.json
scripts/__tests__/griddle-test.js
scripts/gridTable.jsx
scripts/gridTitle.jsx
scripts/griddle.jsx

Work in progress for filtering just by columns with a rudimentary example. The approach that we're taking is to say "use a custom heading component combined with a built in filterByColumn method". We are going this route because we want to avoid locking people into our styling on that.

Add column filters

---

build/Griddle.js
scripts/griddle.jsx

When i tried to use isMultipleSelection in griddle. I got select all box error like this this._updateSelectedRowIds not defined. "this" inside the forEach loop points to this loop row only. So, I assigned this to some other variable, and used it.
```
var self = this;
forEach(visibleRows, function (row) {
self._updateSelectedRowIds(row[self.props.uniqueIdentifier], newSelectedRowIds, newIsSelectAllChecked);
}, this);
```

Select All Box Bug Fix

---

scripts/deep.js

This PR fixes #228. It based on #229, but also solves problem with sorting, which uses getAt (getPath).

Support columns with dots

---

scripts/gridTitle.jsx

Fix for columns with same "displayName"

---

scripts/gridRow.jsx
scripts/gridTable.jsx
scripts/gridTitle.jsx

Fix numeric string value for CSS property

---

Gruntfile.js
docs/assets/index.html
docs/src/template/template.jst
package.json
scripts/__tests__/griddle-test.js
scripts/griddle.jsx

Use React 15 and remove all instances of setProps :shame:

Use React 15

---

scripts/griddle.jsx

This will fix [#352] (https://github.com/GriddleGriddle/Griddle/issues/352).

Update column metadata props data

---

docs/src/markdown/customization.md
scripts/customPaginationContainer.jsx
scripts/griddle.jsx

allow passing options to custom pager component

[pagination] add custom pager options

---

.gitignore
build/Griddle.js
modules/columnProperties.js
modules/customFilterContainer.jsx.js
modules/customPaginationContainer.jsx.js
modules/customRowComponentContainer.jsx.js
modules/deep.js
modules/gridFilter.jsx.js
modules/gridNoData.jsx.js
modules/gridPagination.jsx.js
modules/gridRow.jsx.js
modules/gridRowContainer.jsx.js
modules/gridSettings.jsx.js
modules/gridTable.jsx.js
modules/gridTitle.jsx.js
modules/griddle.jsx.js
modules/rowProperties.js
package.json

include `modules` folder in repo to allow for direct reference to branch/commit via npm:
example:
```
"dependencies": {
"axios": "^0.11.0",
"bootstrap": "^3.3.6",
"font-awesome": "^4.6.1",
"griddle-react": "https://github.com/GriddleGriddle/Griddle.git#6033869",
```

[gitignore] remove modules (include in repo)

---

modules/gridRow.jsx.js

This is a tiny PR to fix issue #398.  This bug is blocking me (and others) from upgrading to 0.6.0 and using the latest features.

Using lodash function that provides correct functionality

---

scripts/griddle.jsx

Please let me know if there is anything else to be done here and I would be happy to follow up.

#66, #30 - Support filterable property in columnMetadata

---

scripts/gridTitle.jsx

See http://webaim.org/techniques/tables/data

Overcome "Empty table header" accessibility error

---

build/Griddle.js
modules/griddle.jsx.js
scripts/griddle.jsx

Fix sorting direction icon when useExternal is set

---

src/components/TableHeadingCell.js
src/plugins/local/components/CellContainer.js
src/plugins/local/components/TableHeadingCellContainer.js
src/plugins/local/selectors/localSelectors.js
src/selectors/dataSelectors.js
stories/index.js

Add custom component / custom heading component

---

build/Griddle.js
modules/griddle.jsx.js

Implements the ability to send props to customNoDataComponent.

Support sending props on customNoDataComponent.

---

conduct.md

Code of Conduct

---

modules/griddle.jsx.js
scripts/griddle.jsx

Set the insensitive sort by default: #466

Feat[Sort]: Use case insensitive sort

---

modules/griddle.jsx.js

similar to https://github.com/GriddleGriddle/Griddle/pull/501
this would be useful/flexible, in case one needs to interact with the DOM upon the Griddle component's state change, and is not using Redux

feature request: allow a custom componentDidUpdate() method to be passed

---

build/Griddle.js
modules/griddle.jsx.js
scripts/griddle.jsx

pursuant to @babenzele 's comments in pull request #521
https://github.com/GriddleGriddle/Griddle/pull/521
I have added the same code change from PR 521 to the source griddle.jsx and ran a grunt build.
It seems to have picked up a few other things, so please review

PR 521 code review: run grunt build

---

build/Griddle.js
modules/griddle.jsx.js
scripts/griddle.jsx

Had some issues where the internal sorting wasn't agreeing with external sort order given, I could've patched this with a custom sort function... but I think this is a cleaner approach. (and less code duplication for when my sorting happens on the server)

Stop sorting internally if using external sort

---

src/components/FilterContainer.js
src/components/FilterEnhancer.js
src/components/NextButtonContainer.js
src/components/NextButtonEnhancer.js
src/components/PreviousButtonContainer.js
src/components/PreviousButtonEnhancer.js
src/components/TableHeadingCellContainer.js
src/components/TableHeadingCellEnhancer.js
src/components/index.js
src/utils/compositionUtils.js
stories/index.js

This PR fixes the issue where if a plugin overwrote the `container` component, events wouldn't be fired.

Trigger events with plugin

---

docs/src/markdown/externalData.md

As per approved issue #79, added function signature and clarification around documentation

Adding function signature for external data documentation.

---

scripts/griddle.jsx

Fix rowMetaData not updated

---

stories/index.tsx

Fix identified in https://github.com/GriddleGriddle/Griddle/issues/649.

Change empty props from void to {}

---

build/Griddle.js
modules/griddle.jsx.js
scripts/__tests__/griddle-test.js
scripts/griddle.jsx

Adding support for column filter function to support an array of values to be filtered by
Adding columnFilterFunc prop to allow customized column filter
Provides resolution of issues: #482 #490

Improvements to column filter functions

---

src/utils/__tests__/columnUtilsTests.js
src/utils/columnUtils.js
stories/index.tsx

Conditional Columns #656

---

stories/index.tsx

1.x
Adds story from [`GriddleList`](https://github.com/GriddleGriddle/griddle-docs/blob/429f318778604c5e7500c1c949fe1c3137972419/components/GriddleList.js) in the [Griddle docs](http://griddlegriddle.github.io/Griddle/examples/asList/).
Trying to prove https://github.com/GriddleGriddle/Griddle/issues/668

Add story with list row demo

---

src/components/ColumnDefinition.js
src/module.d.ts
src/plugins/local/selectors/__tests__/localSelectorsTest.js
src/plugins/local/selectors/localSelectors.js
stories/index.tsx

1.x
Ports https://github.com/GriddleGriddle/Griddle/pull/436 forward.
Also cleans up filter logic a bit, including skipping filtering altogether unless a filter has been specified.
Closes #712 
Story!

Filterable

---

src/reducers/dataReducer.js
src/selectors/__tests__/dataSelectorsTest.js
src/selectors/dataSelectors.js
src/utils/dataUtils.js

1.8
To make loading rows faster
Yes

Improve performance

---

package.json
src/index.js

1.x
Fix server side rendering where window is not available
Either there are no test that cover this area or the test runner creates a window object

Check for existence of window before using it

---

package.json

Release 1.13.1
