build/griddle.js
scripts/gridTitle.jsx

It would be really helpful to have only certain columns be sortable. I'm thinking this should be a property in columnMetadata items:
```
[
{
"columnName": "name",
"sortable": false,
"displayName": "Name"
},
{
"columnName": "location",
"sortable": true,
"displayName": "Location"
},
...
]
```

Added sortable property to column metadata

---

package.json

`~1.6.0` rejects underscore v1.7.0. Peer dependencies [need to be lenient](http://blog.nodejs.org/2013/02/07/peer-dependencies/), otherwise this needs to be a f'real dependency, as I understand it.
Updated to `1.x` to allow future versions <2.0.0.

Lenient peer dependency on underscore.

---

scripts/gridTitle.jsx
scripts/griddle.jsx

This should fix #70 as soon as #71 is merged with some minor modifications. I've added a `headerClassName` and `headerStyles` property to Griddle so that someone can override the default header styling. 
Happy to hear feedback on implementation but it's pretty straight forward.

Add headerClassName and headerStyles props to Griddle and GriddleTitle.

---

build/griddle.js
examples/infiniteScroll/infiniteScroll.html
examples/infiniteScroll/infiniteScrollFixedHeader.html
scripts/gridRow.jsx
scripts/gridRowContainer.jsx
scripts/gridTable.jsx
scripts/griddle.jsx
scripts/rowProperties.js

Currently missing fields cause the grid to render values in offset under the wrong columns.
This change introduces default empty values for missing columns.
A new slim data view was added which holds default values for any missing columns and does not alter the original data.

Add support for empty columns so items will be rendered under the matching column. 

---

build/griddle.js
scripts/__tests__/griddle-test.js
scripts/gridRow.jsx
scripts/gridRowContainer.jsx
scripts/gridTable.jsx
scripts/griddle.jsx

Added onRowClick event to Griddle, passing it down to GridRow. The callback receives the gridRow component and the event. The gridRow is and instance of GridRow which has a 'props' property which has 'data', 'columnSettings', 'rowSettings', etc. This does not consider child-tables, yet. Usage example:
``` javascript
function(gridRow, event) {
console.log("Grid row clicked with data:", gridRow.props.data);
}
// ...
<Griddle onRowClick={onRowClick} />
```

Add Row Events: onRowClick #64

---

docs/assets/index.html
scripts/gridRow.jsx
scripts/gridRowContainer.jsx
scripts/griddle.jsx
scripts/rowProperties.js

This allows custom table rows to be created. Documentation still needs to be updated and it would likely be good to state that the names on the custom components will likely change before ver 1 is out (aka customRow and customTableRow components are kind of confusing names).
A rough example of a `customTableRowComponent` is as follows: 
``` 
var CustomRow = React.createClass({
getInitialState: function() {
return { editToggled: false };
},
handleClick: function(e){
this.setState({editToggled: !this.state.editToggled });
},
render: function(){
if(this.state.editToggled){
var cols = _.map(_.pairs(this.props.data), function(col, index){
return <td><input type="text" defaultValue={col[1]} style={{width: "100%", height: "100%", color: "#CCC"}} />{index === _.pairs(this.props.data).length -1 ? …
```

Add custom table row component

---

.gitignore
build/griddle.js
scripts/gridRow.jsx
scripts/gridRowContainer.jsx
scripts/gridTable.jsx
scripts/gridTitle.jsx
scripts/griddle.jsx

- does not support subgrids
- the selection is reset when sorting / paging / filtering
- the selection is not reset when paging with infinite scroll

Multiple selection

---

bower.json

I added the `bower.json` file to just add it to bower. You have to register it afterwards as bower component. This allows people to integrate Griddle much easier when not using NPM.
For instance I will use it with [Rails Assets](https://rails-assets.org).

Add Griddle to bower

---

Gruntfile.js
build/griddle.js
scripts/__tests__/gridRow-test.js
scripts/__tests__/griddle-test.js
scripts/deep.js
scripts/gridRow.jsx
scripts/griddle.jsx

This change allows griddle to access nested object properties as columns and refer to those columns in the columnMetaData.  
`{
prop1: 1212,
prop2: {
nestedProp1: "something",
nestedProp2:  "other thing"
}
}`

Adding nested property columns, fixing broken unit tests

---

docs/src/markdown/customization.md

To Whomever it May Concern,
First wanted to start off by saying thank you for building this awesome plugin!
I am building a Flux app using Alt, and needed a way to pass an actions object down to a column custom component as a prop. After further examining the source code, I noticed that the `metadata` property is being passed down to the component, and the action can be specified in the `customColumnMetadata` object.
However, the documentation did not mention any of these things. This PR updates the docs to better reflect this information. Please let me know if I need to change anything.
This is related to [this issue](https://github.com/GriddleGriddle/Griddle/issues/225)

Updating customization.md document to include information about custom column component metadata

---

scripts/gridTable.jsx

If showPager fluxes between true and false, having `var pagingContent = ""` (which is equal to `var pagingContent = <span />;`) results in invariant violation (at least in Chrome). Change it to `<tbody />` solves all problems for me.

Fix invariant violation by showPager

---

package.json

allow jest to run since 0.5.x supports iojs v2 and higher

lock jest cli to version 0.4.19

---

build/griddle.js
examples/customization/testChart.html
scripts/griddle.jsx

@ryanlanciaux  I understood discussion about duplicate functionality but the griddle-react package in npm needs this, like me right now. 
This is a very simple implementation, you pass all the data throw ```gridMetadata``` to the custom grid component. The only concern I have is about passing ```data``` or ```className``` because I didn't pass the metadata throw some scope like ```gridData``` just because I didn't like to create a extra scope for avoid these mistake, however, this is easy to change and depend of you.
About unit testing, you are using ```jest```, jest using ```iojs``` instead of node. I could't get it run properly. 
My suggestion is try to choose stack that people know, the big problem with JS is that one, too many packages with the same objective and I can't deal with …

Added gridMetadata

---

scripts/gridRowContainer.jsx

Subgrids of subgrids were not properly setting columnMetadata.  This caused things like CustomComponents to not be applied to subgrids of subgrids.

Fix for issue #163.

---

.travis.yml

Travis CI `before_install` uses `npm install -g grunt-cli jest-cli` which is installing `jest-cli@0.7.0 `.
Travis CI build will fail current tests with`jest-cli@0.7.0`.
```
$ jest
/home/travis/.nvm/v0.10.40/lib/node_modules/jest-cli/bin/jest.js:12
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
```
To make it consistent, we should just `npm test` and use jest from package.json instead of using jest-cli installed from `npm install -g  jest-cl`.
See Travis CI build error here -  https://travis-ci.org/GriddleGriddle/Griddle/builds/89018241

Remove jest-cli from before_install (global) and use `npm test` instead of jest

---

scripts/gridTable.jsx
scripts/griddle.jsx

This fixes the following issue with React 0.14:
```
Warning: validateDOMNesting(...): <span> cannot appear as a child of <table>. See Griddle > GridTable > table > span.
```
Also removes the unused "tableHeading" prop from GridTable.

React 0.14 compatibility fixes

---

.travis.yml
jest/preprocessor.js
karma.conf.js
package.json
scripts/__tests__/gridFilter-test.js
scripts/__tests__/gridPagination-test.js
scripts/__tests__/gridRow-test.js
scripts/__tests__/gridSettings-test.js
scripts/__tests__/gridTitle-test.js
scripts/__tests__/griddle-test.js

This PR migrates our tests away from Jest over to Karma so that we are able to run them in 0.10 and higher.  As of the upgrade to 0.14 (#262) the version of Jest does not support node versions lower than 4 and iojs 2. 
Test run against node's 0.10 thru 5:
https://travis-ci.org/kevinold/Griddle/builds/92616940

Migrate away from Jest to Karma

---

scripts/griddle.jsx

This adds a check that prevents the default container styles being applied to CustomRowComponentContainer if useGriddleStyles is false.

Only use default styling for CustomRowComponentContainer if useGriddleStyles is true

---

docs/src/markdown/infiniteScroll.md

Add cautions section note about using the "key" attribute on rowMetadata when re-rendering a table with infinite scrolling enabled.

Add caution/warning to infiniteScroll.md documentation

---

package.json

Griddle's throwing an error when trying to install alongside React 0.14.5.

Fix bug with React peer dependency version

---

scripts/customRowComponentContainer.jsx
scripts/griddle.jsx

This is a pull request that is detailed in #286, and a refining of the now closed PR #295.  The `globalData` prop passed into Griddle will be sent in as a prop to each customRowComponent instance allowing the row component to have access to any user-specified global data.  Without this a custom row component is in somewhat of a "black box" and requires inefficient methods to access state that isn't row specific (like having to connect each row to a flux/redux store).  Right now the `globalData` prop is only passed into instances of customRowComponent, but this could potentially be used in other places since the data can be as generic as a developer wants.

 Add globalData prop to pass in user-specified global data through Griddle component to every customRowComponent instance.

---

scripts/gridRow.jsx

Fix for the following issue:
The component or characters that are added into the first column of a subgrid row
(parentRowCollapsedComponent and parentRowExpandedComponent, default or custom) are
not displayed when a metadata object (from columnMetadata) exists for this first column.

Subgrid Icons Not Displayed if Metadata Present

---

scripts/gridRowContainer.jsx
scripts/griddle.jsx

We're using a webpack/browserify-style bundler internally (to be open-sourced at some point) that only supports es6-style requires at the top of the file, so a dynamic require like used here to resolve a circular dependency doesn't work. I changed the code to have griddle inject the class instead.
cc @kevinhughes27

Remove circular dependency between griddle and gridRowContainer

---

scripts/gridTitle.jsx

Hey,
In my opinion, if the column is not sortable, I don't need to see the default sort component.

Make non-sortable column default icon hidden

---

scripts/gridTitle.jsx

This is related to #35 - it adds the ability to specify a custom header component (and to pass arbitrary properties).
There is one thing that is not general, however -- in order to function, it ascends the DOM tree from the header looking for a `<th>` tag, which it assumes is the encapsulating Griddle header tag. This will fail in the event that your custom header component includes its own `<th>` tag.

implement custom headers

---

build/Griddle.js
build/griddle.js
scripts/gridTable.jsx

The cell used for the NoData component did not have a colspan applied, meaning that narrow columns would cause the contents to wrap unnecessarily or would not allow for centre aligning the content.
Before:
After:

NoData Component has no colspan

---

scripts/griddle.jsx

This PR can be used as solution for #337, #290, #250, #142 and #116.
Example for #142:
```
var columnMeta = [{
columnName: "col1",
displayName: "COL1",
sortable: true,
compare: function(item) {
return new Date(item);
}
}, ...]
```
Example for #116, #290 (with naturalSort from [javascript-natural-sort](https://www.npmjs.com/package/javascript-natural-sort)):
```
var columnMeta = [{
columnName: "col1",
displayName: "COL1",
sortable: true,
compare2: function(a, b) {
return naturalSort(a, b);
}
}, ...]
```
- **compare** is used for underscore-style sortBy method (with 1 argument)
- **compare2** is used for standard JS sort method (with 2 arguments)

Add custom column sorting possibility

---

build/Griddle.js
scripts/griddle.jsx

When re-rendering Griddle with a different ```resultPerPage``` prop, it won't affect the results.
Lets say we have a wrapper component that holds in its state the number of results per page, and this number is being changed by another component outside of Griddle.
Currently Griddle won't use the new ```resultsPerPage``` value, won't set the page size, and won't re-render the grid.
Example:
```
...
getInitialState() {
return {
myResultsPerPage: 5
};
}
onChange(newResults) {
this.setState({ myResultsPerPage: newResults });
}
render() {
return (
<Griddle
....
resultsPerPage={this.state.myResultsPerPage}
/>
);
}
```

feat(pagination): allow changing resultsPerPage outside of GridSettings

---

scripts/gridTable.jsx

Fixed defaultColSpan when using externalLoadingComponent and not using griddlestyles.
Moving the set statement of defaultColSpan out of the if where it checks whether the table is using griddle styles.
Previously this caused externalLoadingComponent to only have colspan = 1 and ending up in the left most column.

Fixed defaultColSpan when using externalLoadingComponent

---

build/Griddle.js
modules/gridRow.jsx.js
scripts/gridRow.jsx

As noted in https://github.com/GriddleGriddle/Griddle/commit/b65bfe8460848f6e3a1a7942c4b1c3ae3c9f4255#commitcomment-17304274 by @adamgruber, the migration to `lodash` broke default values - in an especially evil way: defaults work for fields with single-character names, but not for anything else. I've just been bitten by this; this change fixes the issue.
```js
> l = require('lodash')
// SNIP
// wrong
> l.fromPairs(['a', 'b'], [])
{ a: undefined, b: undefined }
> l.fromPairs(['aaa', 'bbb'], [])
{ a: 'a', b: 'b' }
// right
> l.zipObject(['a', 'b'], [])
{ a: undefined, b: undefined }
> l.zipObject(['aaa', 'baa'], [])
{ aaa: undefined, baa: undefined }

Fix defaults for missing fields in results

---

scripts/gridRow.jsx

Currently booleans are rendered as an empty cell
This change causes them to be coerced to string before passing to react to render
-----------------------------------
I think the next step to this pr would be to add a `DefaultCell` component (i.e. just the span creation logic) with a formatter

Format booleans correctly

---

build/Griddle.js
scripts/griddle.jsx

"Rows per page" selectbox doesn't update when using external data source. This patch fixed the problem.

Fixed External Source 'Rows per page' value problem

---

modules/griddle.jsx.js

Commit 26b44f sought to fix the external source 'rows per page' value
problem but did not update the modules/griddle.jsx.js, which is required
for users who install Griddle via npm.

Fix 'Rows per page' value problem for npm users

---

modules/griddle.jsx.js

this would be useful, in case one needs to interact with the DOM after the Griddle table is rendered

feature request: allow a custom componentDidMount() method to be passed

---

build/Griddle.js
modules/gridRow.jsx.js
modules/gridTitle.jsx.js
modules/griddle.jsx.js
scripts/gridRow.jsx
scripts/gridTitle.jsx
scripts/griddle.jsx

I've implemented an onSelectionChange callback that the user can use. I needed it for a project of mine and couldn't figure out how to get Griddle 1.0 working, so here are my changes. 
A number of these changes are cosmetic, the formatting in the existing multiple selection code was pretty inconsistent.
I don't know why my `.js` files are so much longer than other peoples' changes, but this is what I got when I built with grunt. 
Please let me know if you have any questions or issues with these commits.

add onSelectionChange and persist selectedRowIds across pages

---

build/Griddle.js
modules/deep.js
modules/griddle.jsx.js
scripts/deep.js
scripts/griddle.jsx

Griddle was ignoring my `Date` constructor in `this.props.results`. 
Also, if a field was missing in the first item in `this.props.results`, Griddle was not showing that column in grid settings. 
Please let me know if you have any issues or questions.

Allow date and generate selected columns options from columnMetadata if it exists

---

build/Griddle.js
modules/griddle.jsx.js
scripts/griddle.jsx

Hi, when I'm using external data Griddle changes the initial sort order that I had given it (asc to desc or vice versa), and this only happens on load.
This fix is to stop it changing sort order on load (changeSort shouldn't be called on init/mount anyway?)

Fix sort when using external

---

build/Griddle.js
modules/griddle.jsx.js
scripts/griddle.jsx

The removed statement overwrites filteredColumns with the columns prop, preventing filteredColumns from being controlled by column settings. This PR allows filteredColumns to be dynamic and controlled externally via state.

Remove unnecessary replacement of filteredColumns

---

build/Griddle.js
modules/deep.js
modules/griddle.jsx.js
scripts/__tests__/deep-test.js
scripts/__tests__/griddle-test.js
scripts/deep.js
scripts/griddle.jsx

This fixes #65 "[make filter queries search through nested divs for custom components](https://github.com/GriddleGriddle/Griddle/issues/65)" which is tagged an [approved issue](https://github.com/GriddleGriddle/Griddle/issues?q=is%3Aopen+label%3Aapproved+no%3Aassignee). I needed exactly this myself, so I implemented it.
The basic feature is; given data like this:
data = [
{
somethingElse: [{ blah: "one",
blah2: ["two"] }],
...
},
...
]
The column filters can now match "one" and "two".
I have some concerns about how this would perform on large objects, but I also think traversing the objects is a pretty good default. This could be implemented a little more efficient for some cases but in a vast majority of cases it should be fine.   
I will implement custom column filters functions on top …

columnFilter to filter nested data

---

src/components/Cell.js
src/plugins/position/components/TableEnhancer.js

Update to infinite scroll plugin to only scroll when a new row will be rendered.

Avoid unnecessary scroll actions

---

build/Griddle.js
examples/properties/properties.html
modules/gridRow.jsx.js
modules/gridRowContainer.jsx.js
modules/gridTable.jsx.js
modules/gridTitle.jsx.js
modules/griddle.jsx.js
scripts/gridRow.jsx
scripts/gridRowContainer.jsx
scripts/gridTable.jsx
scripts/griddle.jsx

The `onRowMouseEnter` and `onRowMouseLeave` props can be passed to `Griddle` component.
This props should contain a function, which will be triggered by onMouseEnter and onMouseLeave events of each row with data.
I have added a functionality and added new props to docs.
UPD: `onRowWillMount` and `onRowWillUnmount` were added

onRowMouseEnter and onRowMouseLeave Griddle events

---

src/plugins/local/reducers/__tests__/localReducerTests.js
src/reducers/__tests__/dataReducerTest.js
src/reducers/dataReducer.js
src/selectors/dataSelectors.js
src/utils/__tests__/dataUtilsTests.js
src/utils/dataUtils.js
stories/index.js

Previously, we were doing a filter against griddle key to get cell values. That could be costly. Add lookup object instead and references this instead of filtering the data for cell values.

Add lookup to avoid costly filter in cell value

---

modules/griddle.jsx.js

#483 Griddle doesn't refresh when item is added / removed / edited during search

Fix[Filter]: Refresh results during filtering

---

src/reducers/__tests__/dataReducerTest.js
src/reducers/dataReducer.js
src/selectors/__tests__/dataSelectorsTest.js
src/selectors/dataSelectors.js

We were not taking ephemeral columns (columns that are made-up of render properties but do not exist in the data) into account when handling the showing/hiding of columns from settings. This addresses that.
_There still needs to be some tests and organization around the reducer changes before merging this one._ 
This one can be tested by cloning the repository followed by `npm install && npm run storybook`. From there, click on the `Bug fixes` -> `Delete row` story (This was for another potential bug but has the same sort of column). Changing the visibility state of the columns from settings should now work as intended.

Fixes #592 - Custom component in settings

---

src/components/TableHeading.js
stories/index.js

Fixes a bug where we were using title as key for TableHeading. If there was a title that was shared between multiple columns, Griddle would throw an error.

Fixes #589 - Fix for same column title

---

src/index.js

1.x
They seem to be typos.
Glad to add, if this is indeed the desired behavior.

Actually map plugin events & settingsComponentObjects

---

.editorconfig
.gitattributes
package.json
src/components/NoResults.js
src/components/NoResultsContainer.js
src/components/Table.js
src/components/TableHeading.js
src/components/__tests__/CellTest.js
src/reducers/__tests__/dataReducerTest.js
src/reducers/dataReducer.js
src/selectors/__tests__/dataSelectorsTest.js
src/selectors/dataSelectors.js
src/utils/__tests__/dataUtilsTests.js
src/utils/dataUtils.js
stories/index.js

1.x
Acknowledging that #618 is a lot to handle, I figure I might as well pull some of it out (plus some changes) that should be easier to review in isolation.
* A few of the trivial storybook fixes from #618
* A few dev environment improvements:
* For LF from Git on Windows
* [cross-env](https://www.npmjs.com/package/cross-env) for builds on Windows
* [EditorConfig](http://editorconfig.org/) for anyone
* `Table`, `TableHeading` and `NoResults` are now generally more resilient
* `NoResults` props actually work
* If `data` is `null` or `undefined`, `NoResults` is rendered instead of runtime errors (with tests!)
* `NoResults` now receives `columnIds` and `columnTitles` (consistent with `TableHeading`; mostly useful for column count)
The primary use case, for which I added a story, is a …

Table/NoResults Improvements

---

src/components/Settings.js
src/components/SettingsContainer.js
src/components/__tests__/SettingsTest.js
src/components/index.js
src/index.js
src/settingsComponentObjects/ColumnChooser.js
src/settingsComponentObjects/index.js
stories/index.js

1.x
* `components` now exports a `SettingsComponents` key with the default components.
* If `component` is not defined on a `settingsComponentObjects` entry, the corresponding key from `components.SettingsComponents` is used.
* This is how the default settings components are specified, as this configuration is most flexible.
* If a settings component cannot be found in `settingsComponentObjects` or `components.SettingsComponents`, the setting is ignored (instead of an error).
* A top-level `settingsComponentObjects` prop can now override default/plugin settings components, as with `components` and `renderProperties`.
* Settings components are now ordered by `order`.
Plus a few stories proving out scenarios that seem interesting.
Hooking into `settingsComponentObjects` didn't really feel …

Settings Component Customization

---

.storybook/webpack.config.js
package.json
src/components/CellContainer.js
src/components/ColumnDefinition.js
src/components/RowDefinition.js
src/module.d.ts
stories/fakeData.d.ts
stories/fakeData2.d.ts
stories/index.js
stories/index.tsx
tsconfig.json

This should close #611, eventually. I figure the questions asked there are better answered with visuals.
> The other thought is would it be possible to test the types via unit tests instead or would that be way more work? I'd love it if there was something that would allow those who are using JavaScript to continue doing so with Griddle codebase but also make life easier for folks who are using Griddle in a typescript project all while ensuring that the types are up-to-date as we make changes in Griddle.
Ultimately type definitions are about codifying valid usage of the library, so they are best tested with real-world use cases. That could be achieved using a [standalone `tsx` test file](https://github.com/NewBoCo/DefinitelyTyped/blob/b16bfba18fc6c227fba117c4e30fa6b5691ce358/griddle-react/ …

WIP: TypeScript Definition + Stories

---

src/index.js
src/module.d.ts
src/plugins/local/components/TableHeadingCellContainer.js
src/utils/index.js
src/utils/sortUtils.js
stories/index.tsx

1.x
1. Two identical default implementations of `setSortProperties` have been replaced with a version in `sortUtils`
2. `LocalPlugin` now respects `events.setSortProperties` before defaulting to the default implementation
3. Functions in the `utils` namespaces are now actually exported
4. Added a story demoing disabling sort on a column, an alternative to @hkasemir's in https://github.com/GriddleGriddle/Griddle/issues/591#issuecomment-292063561
5. Type definitions for `sortUtils`
@hkasemir nerd sniped me:
> would be interested to know if there is a method that's more built-in, though!
I'm curious if anyone can think of a clean extensibility pattern that would allow either the custom `setSortProperties` or Heidi's `CustomSortTableHeader` to access a custom prop on `<ColumnDefinition />`. …

setSortProperties adjustments + demo of unsortable column

---

src/components/CellContainer.js
src/components/TableHeadingCellContainer.js
src/plugins/local/components/TableHeadingCellContainer.js
stories/index.tsx

1.3.0
Props "cssClassName" and "headerCssClassName" of the ColumnDefinition component are now taken in consideration to compute class names of td and th elements.
The two props are documented but currently ignored
Closes #583 #641

Fix #583 - Use of ColumnDefinition's cssClassName and headerCssClassName props

---

src/components/CellContainer.js
src/components/ColumnDefinition.js
src/components/RowContainer.js
src/components/RowDefinition.js
src/components/TableBody.js
src/components/TableHeadingCellContainer.js
src/module.d.ts
src/plugins/local/components/RowContainer.js
src/plugins/local/components/TableHeadingCellContainer.js
src/plugins/local/selectors/localSelectors.js
src/selectors/dataSelectors.js
src/utils/valueUtils.js
stories/index.tsx

1.*
1. `rowDataSelector` is no longer limited to `LocalPlugin`
2. `rowData` and `index` (on current page) have been added to `Row` `props`.
3. `RowDefinition` `cssFunction` is now called if it exists to get a `Row`'s `className`.
The expected signature of `cssFunction` was unclear, so I ultimately opted for accepting the `Row`'s `props`, which seems more flexible than the `rowData` and `index` I initially implemented.
Setting the current implementation aside, I wonder about renaming `cssFunction` as `cssClassName` (aligned with the `ColumnDefinition` prop, and not a breaking change since it has never worked) and allowing both to accept either a function (which we would call with the current `Row`/`Cell` `props`) or a plain string.
Fixes #643
No, but there's a story!

Implement RowDefinition cssFunction

---

src/components/TableHeadingCellContainer.js
src/module.d.ts
src/plugins/local/components/TableHeadingCellContainer.js
stories/index.tsx

1.x
`sortable`, which was already defined on `ColumnDefinition`, is now respected.
I also added a default `cursor: pointer` style to `sortable` columns. It occurs to me that there's not a great way to override this that is `sortable`-aware. Should we add `style`/`headerStyle` props to `ColumnDefinition` in imitation of `cssClassName`/`headerCssClassName`?
Fixes #591.
Fixes #652. cc @andreme
Story!

Support ColumnDefinition Sortable

---

.babelrc

1.x
Add lodash plugin to babelrc build config
Currently the `babel-plugin-lodash` is only used by the babel-loader in the webpack build but since the `build-modules` npm script calls babel directly, the lodash plugin needs to be added to the babelrc also otherwise calling `import Griddle from 'griddle-react'` will also import all of lodash.
You can see it on line 23 here: https://unpkg.com/griddle-react@1.3.1/dist/module/index.js
Don't think there is any easy way to test for this

Avoid importing entire lodash package

---

src/plugins/local/selectors/localSelectors.js
src/utils/__tests__/columnUtilsTests.js
src/utils/columnUtils.js
stories/index.tsx

1.x
It's still not clear to me what precisely is causing the order to change, but it seems wise in general to set column `order` earlier to use everywhere (which fixes the bug).
Also cleaned up `columnUtils` a bit. 
Fixes #619.
Story!

Fixed Many-ColumnDefinition Ordering

---

src/module.d.ts

1.3
Remove implicit any
Because we can't force people to use implicit any mode (`"noImplicitAny": false`) with typescript :smile:

Suppress implicit any

---

src/components/Pagination.js
src/components/SettingsContainer.js
src/module.d.ts
stories/index.tsx

1.6
1. Cleans up obsolete `Pagination` props
2. Adds an example of moving the page size component into `Pagination`
3. Fixes disabling a settings component by clearing its key on `SettingsComponent`
4. Fixes `GriddleComponent<T>` signature, which had apparently never _really_ been tested
* Discovered with the next commit...
* But also discovered by compiling an existing app against Griddle 1.6, which includes https://github.com/GriddleGriddle/Griddle/commit/02be19d29b956a000cc9b2b4cc4cd5583f3891db. `ColumnDefinition` had previously been exported without a type, so the types passed to `customComponent` had not been checked.
Who doesn't love more stories? Also, TypeScript should work.
Stories!

TypeScript Fix + Pagination with Size Setting

---

src/components/CellContainer.js
src/components/TableHeadingCellContainer.js
src/module.d.ts
src/plugins/local/components/TableHeadingCellContainer.js
stories/index.tsx

1.x
Expand `ColumnDefinition` `extraData` into `props` for `TableHeadingCell`, `Cell`, `customHeadingComponent` and `customComponent`.
The [v0 implementation of `globalData`](https://github.com/GriddleGriddle/Griddle/pull/302) passed `globalData` through directly; it's trivial to switch this implementation to pass through an `extraData` prop, if that would be preferred.
Closes #674 
Story!

Implement ColumnDefinition extraData

---

src/components/Layout.js
src/components/LayoutContainer.js
src/components/index.js
src/index.js
src/module.d.ts
src/module.js
src/plugins/legacyStyle/index.js
stories/index.tsx

1.x
* `styleConfig` from plugins is now merged in between default styles and the `styleConfig` user prop
* The default `Layout` now renders a `Style` component (default renders `null`) that plugins and users can override to inject a stylesheet
* Gives a mechanism for including a new default "theme" via plugin (#661)
* Gives a mechanism for others to contribute themes (#667)
Incomplete story - I pulled in the [CSS from v0](https://github.com/GriddleGriddle/Griddle/blob/359f3f1243b857373b8892a0ff93d60797152f60/docs/assets/styles/griddle.css), but don't know v0 well enough to fix it up to look nice.

Plugin styleConfig and components.Style

---

src/components/Cell.js
src/components/Row.js
src/module.d.ts
stories/index.tsx

1.x
- Closes #678 with a story that demonstrates providing `Row` and `Cell` with event handlers, via enhancers
- Replaces naive `GriddleComponents` (type of `Griddle.components` and `GriddlePlugin.components`) with a more complete definition:
- `Enhancer`, `Container` and `ContainerEnhancer` companions are now included for all components 
- `RowDefinition` and `ColumnDefinition` have been removed
- Adds types to mouse event handlers
Types are neat. Examples are neat, too.
Stories!

TypeScript: Rewrite GriddleComponents + (Row/Cell Events Example)

---

package.json
src/module.d.ts
stories/index.tsx

1.x
The good news is TypeScript 2.4 found some type ambiguities.
The bad news is that the React type definitions upgrade isn't backwards-compatible (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17288), so we either have to upgrade or pin an older version of `@types/react`.
So we upgrade. Fixes #686.
The compiler is a test.

Typescript Upgrade

---

src/components/TableHeadingCellContainer.js
src/plugins/local/components/TableHeadingCellContainer.js
src/utils/sortUtils.js
stories/index.tsx

1.x
Applies `TableHeadingCellAscending` and `TableHeadingCellDescending` as `className` on the `<span>` that surrounds the sort icon.
Also, extracts a `getSortIconProps` utility function that can be shared between the default and local plugin `TableHeadingCellContainer` implementations.
Fixes #698
cc @moraleslos
Story!

Sort Icon Classes

---

src/components/TableHeadingCellEnhancer.js
stories/index.tsx

1.x
Pass full `sortProperty` to `events.onSort`, if available.
Note that the initial call only includes `id`, not `sortAscending`. Easy enough to hard-code that to `true`, as in [`setSortProperties`](https://github.com/GriddleGriddle/Griddle/blob/1d7b763215c016fa73d700deec98d5edc56fcbe7/src/utils/sortUtils.js#L30), but it _may_ be useful to be able to identify if this was the initial sort?
It is right and good, and also closes #716 (cc @jariwalabhavesh)
`/shrug`

onSort event argument

---

src/utils/index.js

1
Add the Griddle connect to something that can be used outside of Griddle.
When making custom components, it's useful to still be able to easily connect to Griddle's store.
Not really but the previous PR utilizes connect directly and I am running one of my projects against a local copy of Griddle with this change (using Griddle's connect)

Add connect to utils out

---

src/components/NextButtonContainer.js
src/components/PreviousButtonContainer.js
src/index.js
src/module.d.ts
src/plugins/local/components/NextButtonContainer.js
src/plugins/local/components/PreviousButtonContainer.js
src/plugins/local/selectors/localSelectors.js
stories/index.tsx

1.x
- Type cleanup for `RowRenderProperties` and `ColumnRenderProperties`, which currently the same as `RowDefinitionProps` and `ColumnDefinitionProps`.
- Rearranges how `initialState` is initialized to accept/override `initialState` from extra `Griddle` props. Everything still seems to work as expected, but please double-check this.
* As a bonus, this allows setting `enableSettings` and `textProperties` without a plugin, as demonstrated with new stories.
- Default `sortMethod` from state is used, if it exists.
- Addressed TODO to get Next/Previous label from `textProperties`
`<Griddle sortMethod={...}>` now works as a high-level hook to override all columns' sort behavior. It does not change default behavior (cc #466).
Stories!

Default sortMethod (plus: initialState from extra props)

---

src/components/TableBodyContainer.js

1.5.0
className and style are fetched from the store but never passed down to the original component.
If a user wants to keep the original TableBody container but wants to override the style or className.
No

Pass down TableBody style and className

---

.storybook/webpack.config.js
.travis.yml
package.json
src/module.d.ts
stories/index.tsx
webpack.config.js

1.8
* Not sure if there's really any value to targeting `dist/examples/storybook.js` rather than throwing the output away.
* It seems like `build-storybook` should have been sufficient, but it doesn't recognize JSX. So we're going with a straight webpack for now.
1. The build should break if types are broken.
2. The types should not be broken.
Kind of?

Add Storybook to build + fix connect type definition

---

package.json
src/module.d.ts
tsconfig.json

1.8.0
Type GriddleActions in alignment with strict checking requirements and change typescript config to be strict by default.
Downstream projects should be able to use the library without having to comply to the libraries policies regarding the strictness of the typescript compiler. The definitions provided as of 1.8.0 don't pass checks for strictNullChecks as the optional keys in GriddleActions are all implicitly typed as 'X | undefined' but that isn't explicit in the objects type. If Griddle's typings are as strict as possible then it will compile in any downstream projects regardless of how lenient or strict they decide to set themselves up. Given it's a 1 line fix and no other strictness violations were found I've also turned on the other strict compiler options to catch this in the …

Making typescript definitions comply with strict checking

---

src/module.d.ts

1.8.0
Fixes type definition bug in #726, now (fortunately) checked by #727.
We like green builds and working type definitions.
Types!

Fix Middleware in type definition

---

src/index.js
src/module.d.ts
src/utils/listenerUtils.js
stories/index.tsx

1.8.0
Adding the ability to have listeners on the store independent of the "visual" part of Griddle. I am envisioning these to be used for running callbacks from the outside world, for example those provided on the "events" object.
Instead of having an event callback passed down to the component that would trigger it, for example on the pagination buttons, a listener function can subscribe to the store and trigger the "onNext" event when the pagination state has changed in the store. This would make for a better separation of concerns between how the state is changed and what has changed. 
I am running into use cases where I want to be listening on the change of a particular plugin's store subset to run an externally provided call-back but would have to hook into UI events in several …

Store listeners proposal

---

src/actions/index.js
src/components/Loading.js
src/components/LoadingContainer.js
src/components/Table.js
src/components/TableContainer.js
src/components/index.js
src/index.js
src/plugins/local/components/TableContainer.js
src/plugins/local/selectors/localSelectors.js
src/selectors/dataSelectors.js
src/utils/dataUtils.js
stories/index.tsx

1.x
1. Providing `data` of `null`/`undefined` no longer blows up with or without `LocalPlugin`.
2. When `data` is `null`/`undefined` we now render a `Loading` component instead of `NoResults`.
User experience can be made less disruptive if the entire Griddle component doesn't need to be replaced by a loading animation (e.g. if a `Settings` component requires fetching new data).
Stories!

Render Loading component when data is null or undefined

---

src/index.js
src/module.d.ts
src/module.js
stories/index.tsx

1.8+
1. Export `connect` directly, so it's more of a drop-in replacement for `react-redux`, i.e.
```diff
-import { connect } from 'react-redux';
+import { connect } from 'griddle-react';
```
2. Add static `storeKey` property, so default can be changed once app-wide
3. The `storeKey` story's `ConnectedComponent` was incorrectly using Griddle's `connect`; now it doesn't, and the demo works. (Bonus: demo's slightly prettier.)
I'm actually using this functionality now across an app, and it's a bit tedious.

Export connect

---

src/index.js

v1
Updates `componentShouldUpdate` to only pass properties that have changed to the `updateState` action.
Previously, if an initial sort value was passed in while data changed, the user-selected sorting option would be reset to the initial value.
To resolve #697
No 😞

Preserve Sort Properties

---

src/utils/__tests__/sortUtilsTests.js
src/utils/sortUtils.js

v1
Fixes a bug that prevents sorting on nested columns (ex: `location.state`)
To fix the bug!
Yep!

Updated sort to allow sorting on nested columns

---

.storybook/webpack.config.js
src/core/index.js
src/core/initialState.js
src/index.js
src/module.d.ts
src/module.js
src/utils/__tests__/compositionUtilsTest.js
src/utils/__tests__/initilizerTests.js
src/utils/compositionUtils.js
src/utils/initializer.js
stories/index.tsx

1.x
Pulls the default+plugin+props composition out of the Griddle constructor into a testable initializer.
This is really just prep to work on supporting function plugins for #733.
Tests are good, especially for this sort of composition (which seems likely to get more complex).
Lots!

Extract Initializer

---

stories/index.tsx

1.x
Adds story to troubleshoot #767
@radziksh is this a reasonably faithful reproduction of your situation? I improvised `SomePageConnected`, but it seems to be approximately what you're trying to achieve. As implemented here, I'm able to filter data from either `input` without losing focus. Thoughts?

Add external filter (via Redux) example

---

src/components/FilterEnhancer.js
src/components/PageDropdownContainer.js
src/components/PageDropdownEnhancer.js
src/components/index.js
src/module.d.ts

1.x
This moves `events.onGetPage` event handling from the default `PageDropdownContainer` into a new `PageDropdownEnhancer`, in alignment with `events` handling in the other enhancers.
`onGetPage` should work with `LocalPlugin` (and other scenarios that replace `PageDropdownContainer`). 
Fixes #672
Existing "with local and events" story now fires `onGetPage` as expected.

Fire onGetPage more reliably

---

package.json
stories/index.tsx

1.x
Fix #777
Also, a fix for:
> CustomFilterComponent is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21400 broke type inference (or rather, defaulting to `any`) for our test store `connect` calls.
Who needs tests when you have types? :trollface:

More types for Redux test store

---

src/actions/index.js
src/module.d.ts
src/reducers/__tests__/dataReducerTest.js
src/reducers/dataReducer.js
src/utils/__tests__/initilizerTests.js
src/utils/initializer.js
stories/index.tsx

1.11
Fixes #781 root cause (cc @sum32)
1. Includes first commit from #783.
2. Added tests for `GRIDDLE_UPDATE_STATE` and adjusted its behavior a bit (e.g. not losing `data`).
3. Updated `actions.updateState` to pass all state through, instead of only `data`, `pageProperties` and `sortProperties`. That limitation was introduced by @joellanciaux way back in #505, but it's not obvious why.
4. Added a story with a minimal repro (changing a `<Griddle />` prop), which I ultimately expanded to demonstrate changing several `<Griddle />` props, including `data` and `styleConfig`.
Changes to props should be reflected in Griddle's store and its rendering.
Tests and stories!

Improve Prop Change/State Update

---

src/index.js
src/utils/__tests__/initilizerTests.js
src/utils/initializer.js

1.11.0
Fix an apparent typo from https://github.com/GriddleGriddle/Griddle/pull/757
A couple of the stories were not working (controlled griddle)
No but there are some fixed stories

Reconcile reducer/reducers

---

src/plugins/local/selectors/__tests__/localSelectorsTest.js
src/plugins/local/selectors/localSelectors.js

1
Closes #725. This fixes the problem of invisible fields getting matched by the filter by updating the filteredDataSelector() condition to exclude griddleKey and any values not covered by a ColumnDefinition if any ColumnDefinitions are present.
Bear in mind that columns corresponding to other React components may still match the filter based on generated HTML properties rendered as part of the value.toString().toLowerCase() expression. At this point the best course of action may be to recommend that such ColumnDefinitions are tagged with `filterable={false}` if it's a significant problem for the user.
The previous `if (filterable === false)` condition meant that `filterable={false}` must be explicitly set on a ColumnDefinition in order for any property returned by row.keySeq() to be …

Stop filter from matching invisible properties

---

src/components/ColumnDefinition.js

1.11.2
Fixes a few `ColumnDefinition` prop type warnings.
Closes https://github.com/GriddleGriddle/Griddle/issues/799
Warnings are sad.
Nah

Adjust ColumnDefinition propTypes

---

src/core/__tests__/corePluginTests.js
src/core/index.js

Accidentally omitted in 3577f8fbeaf480f316e29e0f701acfcf108637c7
1.11.x
Fix #801 
I broke it
Yep

Include settingsComponentObjects in CorePlugin

---

src/module.d.ts
src/plugins/local/reducers/__tests__/localReducerTests.js
src/plugins/local/reducers/index.js
src/plugins/local/selectors/__tests__/localSelectorsTest.js
src/plugins/local/selectors/localSelectors.js
stories/index.tsx

Git fail. This all belongs to #747 to close #746.

adds object/function filter to local plugin

---

src/components/TableHeadingCellContainer.js
src/components/TableHeadingCellEnhancer.js
src/plugins/local/components/TableHeadingCellContainer.js
stories/index.tsx

1.x
`onSort` is now fired just before the new `sortProperties` are dispatched.
This essentially renders `TableHeadingCell` obsolete, but deleting it is a potentially breaking change.
What if events were fired from a Redux middleware instead of click handlers?
Close #716; #717 was insufficient.
Existing story now demonstrates expected behavior.
It seems like a new React version changed behavior when `render()` returns a string, so the TS story has been adjusted.

onSort with *correct* sortProperties

---

package.json

Trying to ship 1.13.0 with latest changes, but working through an npm issue.
Per recent Gitter conversation, adding a `prepare` step to build when installed from GitHub. @chrisortman, can you verify this works as expected if you install `GriddleGriddle/Griddle#v1.13.0`?

Release 1.13.0

---

.travis.yml
package.json
stories/index.tsx

1.13.1
* Fixes Storybook use of `PropTypes` (#654)
* Removes lone `TableContainer` story, from a simpler time (f70a712dea7cb1460b414062a8257648e1a05efd)
Fixes #826 
Compiler!

@types/prop-types

---

package.json

v1
Upgrade typescript to ^2.8.0
This should hopefully fix error in travis build step `npm run check-ts`
Error:
```
node_modules/@types/recompose/index.d.ts(23,47): error TS2304:
Cannot find name 'Exclude'.
```
Failing builds:
https://travis-ci.org/GriddleGriddle/Griddle/builds/441174637
https://travis-ci.org/GriddleGriddle/Griddle/builds/450669719
Reason: The Exclude keyword used in @types/recompose was added in
Typescript 2.8
(https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#predefined-conditional-types).
Successful CI is the test.

Upgrade typescript to ^2.8.0

---

package.json

v1
Upgrade recompose to ^0.25.1
This is the first version of recompose "officially" compatible with React 16.
(https://github.com/acdlite/recompose/pull/530#issuecomment-332285889)
Griddle react seems to work fine in React 16 without this change.
#823 would achieve the same result, but seems to have failing CI tests.
This is minimal change required to resolve warning `"griddle-react > recompose@0.21.2" has incorrect peer dependency` from npm/yarn.
No additional tests.

Upgrade recompose to ^0.25.1
